/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and dependency status */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chains this deployment can trace */
        get: operations["chains_api_v1_chains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check an address without tracing it
         * @description Cheap, offline pre-check for a complaint-intake form.
         *
         *     Catches transcription errors at the point of entry, where the victim can
         *     still be asked to re-read the address, rather than after a trace returns
         *     nothing.
         */
        get: operations["validate_api_v1_validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trace a wallet and attribute it to a VASP */
        post: operations["trace_api_v1_trace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sanctions and label screening, no tracing
         * @description Instant corpus lookup.
         *
         *     Separate from ``/trace`` because screening must stay fast enough to run
         *     inline on every complaint at intake, and it needs no network at all.
         */
        get: operations["screen_api_v1_screen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddressProfile
         * @description Aggregate behaviour of a single address. Drives behavioural inference.
         */
        AddressProfile: {
            /** Address */
            address: string;
            chain: components["schemas"]["Chain"];
            /** First Seen */
            first_seen?: string | null;
            /** Last Seen */
            last_seen?: string | null;
            /**
             * Transfer Count
             * @default 0
             */
            transfer_count: number;
            /**
             * Inbound Count
             * @default 0
             */
            inbound_count: number;
            /**
             * Outbound Count
             * @default 0
             */
            outbound_count: number;
            /**
             * Unique Senders
             * @default 0
             */
            unique_senders: number;
            /**
             * Unique Receivers
             * @default 0
             */
            unique_receivers: number;
            /**
             * Total Received Usd
             * @default 0
             */
            total_received_usd: string;
            /**
             * Total Sent Usd
             * @default 0
             */
            total_sent_usd: string;
            /** Balance Native */
            balance_native?: string | null;
            /**
             * Is Contract
             * @default false
             */
            is_contract: boolean;
            /**
             * Is Truncated
             * @default false
             */
            is_truncated: boolean;
        };
        /**
         * Attribution
         * @description A ranked, evidenced claim that funds reached a named VASP.
         */
        Attribution: {
            /** Vasp Name */
            vasp_name: string;
            category: components["schemas"]["VaspCategory"];
            chain: components["schemas"]["Chain"];
            /** Matched Address */
            matched_address: string;
            method: components["schemas"]["AttributionMethod"];
            /** Confidence */
            confidence: number;
            /** Hops From Subject */
            hops_from_subject: number;
            /**
             * Value Usd
             * @default 0
             */
            value_usd: string;
            /**
             * Taint Ratio
             * @default 0
             */
            taint_ratio: number;
            /** First Deposit At */
            first_deposit_at?: string | null;
            /** Last Deposit At */
            last_deposit_at?: string | null;
            /** Asset Breakdown */
            asset_breakdown?: {
                [key: string]: string;
            };
            /** Evidence Tx Hashes */
            evidence_tx_hashes?: string[];
            /** Reasoning */
            reasoning?: string[];
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** @default unknown */
            kyc_tier: components["schemas"]["KycTier"];
            /**
             * Fiu Ind Registered
             * @default false
             */
            fiu_ind_registered: boolean;
            /** Compliance Contact */
            compliance_contact?: string | null;
            /** Deposit Address */
            deposit_address?: string | null;
        };
        /**
         * AttributionMethod
         * @description How an address came to be attributed. Ordered by evidentiary strength.
         * @enum {string}
         */
        AttributionMethod: "direct_label" | "deposit_address_heuristic" | "cluster_match" | "behavioural_inference";
        /**
         * Chain
         * @enum {string}
         */
        Chain: "tron" | "ethereum" | "bsc" | "polygon" | "arbitrum" | "bitcoin";
        /**
         * FraudTypology
         * @enum {string}
         */
        FraudTypology: "investment_scam" | "task_based_fraud" | "sextortion" | "ransomware" | "phishing" | "darknet" | "layering" | "undetermined";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvestigativeAction
         * @description A concrete next step for the investigating officer, ranked by urgency.
         */
        InvestigativeAction: {
            /** Priority */
            priority: number;
            /** Action */
            action: string;
            /** Rationale */
            rationale: string;
            /** Target */
            target?: string | null;
            /** Deadline Hint */
            deadline_hint?: string | null;
        };
        /**
         * KycTier
         * @enum {string}
         */
        KycTier: "full_kyc" | "partial_kyc" | "no_kyc" | "unknown";
        /**
         * NodeRole
         * @enum {string}
         */
        NodeRole: "subject" | "intermediary" | "vasp_deposit" | "vasp_hot" | "mixer" | "bridge" | "contract" | "terminal";
        /** RiskAssessment */
        RiskAssessment: {
            /** Score */
            score: number;
            level: components["schemas"]["RiskLevel"];
            /** Signals */
            signals?: components["schemas"]["RiskSignal"][];
            /** @default undetermined */
            typology: components["schemas"]["FraudTypology"];
            /**
             * Typology Confidence
             * @default 0
             */
            typology_confidence: number;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "critical" | "high" | "medium" | "low" | "info";
        /** RiskSignal */
        RiskSignal: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            level: components["schemas"]["RiskLevel"];
            /** Weight */
            weight: number;
            /** Detail */
            detail: string;
            /** Evidence */
            evidence?: string[];
        };
        /** TraceEdge */
        TraceEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            chain: components["schemas"]["Chain"];
            /** Asset Symbol */
            asset_symbol: string;
            /** Total Amount */
            total_amount: string;
            /**
             * Total Usd
             * @default 0
             */
            total_usd: string;
            /**
             * Transfer Count
             * @default 1
             */
            transfer_count: number;
            /** First Seen */
            first_seen?: string | null;
            /** Last Seen */
            last_seen?: string | null;
            /** Tx Hashes */
            tx_hashes?: string[];
        };
        /** TraceNode */
        TraceNode: {
            /** Address */
            address: string;
            chain: components["schemas"]["Chain"];
            /** Depth */
            depth: number;
            /** @default intermediary */
            role: components["schemas"]["NodeRole"];
            /** Label */
            label?: string | null;
            /** @default unknown */
            category: components["schemas"]["VaspCategory"];
            /**
             * Value In Usd
             * @default 0
             */
            value_in_usd: string;
            /**
             * Value Out Usd
             * @default 0
             */
            value_out_usd: string;
            /**
             * Taint Ratio
             * @default 0
             */
            taint_ratio: number;
            /** Arrived At */
            arrived_at?: string | null;
            profile?: components["schemas"]["AddressProfile"] | null;
            /**
             * Risk Score
             * @default 0
             */
            risk_score: number;
            /** Stop Reason */
            stop_reason?: string | null;
        };
        /** TraceRequest */
        TraceRequest: {
            /**
             * Address
             * @description Victim-reported wallet address. Wrappers and stray punctuation from complaint free-text are tolerated.
             * @example TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t
             */
            address: string;
            /**
             * Complaint Id
             * @description NCRP acknowledgement number
             */
            complaint_id?: string | null;
            /** Reported Amount Inr */
            reported_amount_inr?: number | null;
            /** Incident Date */
            incident_date?: string | null;
            /** Max Hops */
            max_hops?: number | null;
            /** Max Nodes */
            max_nodes?: number | null;
        };
        /** TraceResponse */
        TraceResponse: {
            /** Complaint Id */
            complaint_id?: string | null;
            result: components["schemas"]["TraceResult"];
        };
        /** TraceResult */
        TraceResult: {
            /** Subject Address */
            subject_address: string;
            chain: components["schemas"]["Chain"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Nodes */
            nodes?: components["schemas"]["TraceNode"][];
            /** Edges */
            edges?: components["schemas"]["TraceEdge"][];
            /** Attributions */
            attributions?: components["schemas"]["Attribution"][];
            risk?: components["schemas"]["RiskAssessment"] | null;
            /** Recommended Actions */
            recommended_actions?: components["schemas"]["InvestigativeAction"][];
            stats?: components["schemas"]["TraceStats"];
            /** Warnings */
            warnings?: string[];
            /** Filtered Summary */
            filtered_summary?: {
                [key: string]: number;
            };
            /** Deception Findings */
            deception_findings?: string[];
        };
        /** TraceStats */
        TraceStats: {
            /**
             * Nodes Explored
             * @default 0
             */
            nodes_explored: number;
            /**
             * Nodes Unreachable
             * @default 0
             */
            nodes_unreachable: number;
            /**
             * Edges Discovered
             * @default 0
             */
            edges_discovered: number;
            /**
             * Max Depth Reached
             * @default 0
             */
            max_depth_reached: number;
            /**
             * Transfers Examined
             * @default 0
             */
            transfers_examined: number;
            /**
             * Upstream Calls
             * @default 0
             */
            upstream_calls: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Elapsed Seconds
             * @default 0
             */
            elapsed_seconds: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Truncation Reason */
            truncation_reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResponse */
        ValidationResponse: {
            /** Input */
            input: string;
            /** Normalized */
            normalized: string;
            /** Is Valid */
            is_valid: boolean;
            /** Candidate Chains */
            candidate_chains: string[];
            /** Is Ambiguous */
            is_ambiguous: boolean;
            /** Supported */
            supported: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * VaspCategory
         * @enum {string}
         */
        VaspCategory: "exchange" | "bridge" | "mixer" | "gambling" | "payment_processor" | "defi" | "sanctioned" | "scam" | "unknown";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chains_api_v1_chains_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    validate_api_v1_validate_get: {
        parameters: {
            query: {
                /** @description Address to check */
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_api_v1_trace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_api_v1_screen_get: {
        parameters: {
            query: {
                address: string;
                chain?: components["schemas"]["Chain"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
