"""The label corpus: which addresses belong to which known entity.

Two sources, with very different evidentiary weight, deliberately kept apart:

* **OFAC SDN** (``ofac_sanctions.json``) -- generated by
  ``scripts/ingest_ofac.py`` from the US Treasury's published list. Ground
  truth: an address here is sanctioned as a matter of public record.
  Confidence 1.0, always.
* **Curated VASP labels** (``vasp_seed.json``) -- hand-maintained claims that a
  named company controls an address. Each carries its own ``confidence`` and
  ``source``, and the loader refuses anything missing either.

The strict-sourcing rule is not bureaucracy. A wrong exchange label sends a
preservation notice to the wrong company and burns the few hours in which
funds can still be frozen, so an unsourced label is rejected at load time
rather than quietly trusted.

Lookups are case-insensitive because EVM addresses arrive in inconsistent
EIP-55 casing; TRON and Bitcoin addresses are case-sensitive but their base58
alphabets make collisions between differently-cased forms impossible.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

from app.config import settings
from app.core.chains import Chain
from app.core.models import KycTier, VaspCategory, VaspRecord

log = logging.getLogger(__name__)


@dataclass
class CorpusStats:
    ofac_entries: int = 0
    curated_entries: int = 0
    rejected_entries: list[str] = field(default_factory=list)
    ofac_publish_date: str | None = None
    by_chain: dict[str, int] = field(default_factory=dict)
    by_category: dict[str, int] = field(default_factory=dict)


class LabelStore:
    def __init__(self) -> None:
        self._by_key: dict[str, VaspRecord] = {}
        self.stats = CorpusStats()

    # -- loading -----------------------------------------------------------

    @staticmethod
    def _key(chain: Chain | str, address: str) -> str:
        chain_value = chain.value if isinstance(chain, Chain) else chain
        return f"{chain_value}:{address.lower()}"

    def _add(self, record: VaspRecord) -> None:
        key = self._key(record.chain, record.address)
        existing = self._by_key.get(key)
        # A sanctions hit must never be displaced by a lower-confidence
        # commercial label for the same address.
        if existing is not None and existing.confidence >= record.confidence:
            return
        self._by_key[key] = record
        self.stats.by_chain[record.chain.value] = (
            self.stats.by_chain.get(record.chain.value, 0) + 1
        )
        self.stats.by_category[record.category.value] = (
            self.stats.by_category.get(record.category.value, 0) + 1
        )

    def load(self, labels_dir: Path | None = None) -> LabelStore:
        directory = labels_dir or settings.labels_dir
        self._load_ofac(directory / "ofac_sanctions.json")
        self._load_curated(directory / "vasp_seed.json")
        log.info(
            "label corpus loaded: %d OFAC + %d curated = %d addresses",
            self.stats.ofac_entries,
            self.stats.curated_entries,
            len(self._by_key),
        )
        return self

    def _load_ofac(self, path: Path) -> None:
        if not path.exists():
            log.warning(
                "no OFAC corpus at %s -- sanctions screening is DISABLED. "
                "Run: python scripts/ingest_ofac.py",
                path,
            )
            return

        payload = json.loads(path.read_text(encoding="utf-8"))
        self.stats.ofac_publish_date = payload.get("publish_date")

        for entry in payload.get("entries", []):
            try:
                chain = Chain(entry["chain"])
            except (KeyError, ValueError):
                continue
            programs = ", ".join(entry.get("programs") or []) or "unspecified"
            self._add(
                VaspRecord(
                    address=entry["address"],
                    chain=chain,
                    name=entry.get("name") or "OFAC-designated entity",
                    category=VaspCategory.SANCTIONED,
                    source=f"OFAC SDN ({self.stats.ofac_publish_date or 'undated'})",
                    confidence=1.0,
                    kyc_tier=KycTier.UNKNOWN,
                    notes=f"OFAC programs: {programs}. {entry.get('remarks') or ''}".strip(),
                )
            )
            self.stats.ofac_entries += 1

    def _load_curated(self, path: Path) -> None:
        if not path.exists():
            log.warning("no curated VASP corpus at %s", path)
            return

        payload = json.loads(path.read_text(encoding="utf-8"))
        for entry in payload.get("entries", []):
            rejection = self._reject_reason(entry)
            if rejection:
                self.stats.rejected_entries.append(rejection)
                log.error("rejected label: %s", rejection)
                continue

            self._add(
                VaspRecord(
                    address=entry["address"],
                    chain=Chain(entry["chain"]),
                    name=entry["name"],
                    category=VaspCategory(entry["category"]),
                    source=entry["source"],
                    confidence=float(entry["confidence"]),
                    jurisdiction=entry.get("jurisdiction"),
                    kyc_tier=KycTier(entry.get("kyc_tier") or "unknown"),
                    fiu_ind_registered=bool(entry.get("fiu_ind_registered")),
                    compliance_contact=entry.get("compliance_contact"),
                    notes=entry.get("notes"),
                    address_role=entry.get("address_role"),
                )
            )
            self.stats.curated_entries += 1

    @staticmethod
    def _reject_reason(entry: dict) -> str | None:
        """Validate a curated entry. Returning a string rejects it."""
        address = entry.get("address", "<missing>")
        for required in ("address", "chain", "name", "category", "source", "confidence"):
            if not entry.get(required) and entry.get(required) != 0:
                return f"{address}: missing required field {required!r}"
        try:
            Chain(entry["chain"])
        except ValueError:
            return f"{address}: unknown chain {entry['chain']!r}"
        try:
            VaspCategory(entry["category"])
        except ValueError:
            return f"{address}: unknown category {entry['category']!r}"
        try:
            confidence = float(entry["confidence"])
        except (TypeError, ValueError):
            return f"{address}: confidence is not a number"
        if not 0.0 <= confidence <= 1.0:
            return f"{address}: confidence {confidence} outside [0, 1]"
        if entry["category"] == VaspCategory.SANCTIONED.value:
            return (
                f"{address}: sanctioned addresses belong in the OFAC ingest, "
                f"not the curated corpus"
            )
        return None

    # -- queries -----------------------------------------------------------

    def lookup(self, chain: Chain, address: str) -> VaspRecord | None:
        return self._by_key.get(self._key(chain, address))

    def is_sanctioned(self, chain: Chain, address: str) -> bool:
        record = self.lookup(chain, address)
        return record is not None and record.category is VaspCategory.SANCTIONED

    def is_known(self, chain: Chain, address: str) -> bool:
        return self._key(chain, address) in self._by_key

    def by_category(self, category: VaspCategory) -> list[VaspRecord]:
        return [r for r in self._by_key.values() if r.category is category]

    def __len__(self) -> int:
        return len(self._by_key)

    def summary(self) -> dict:
        return {
            "total_addresses": len(self._by_key),
            "ofac_entries": self.stats.ofac_entries,
            "ofac_publish_date": self.stats.ofac_publish_date,
            "curated_entries": self.stats.curated_entries,
            "rejected_entries": self.stats.rejected_entries,
            "by_chain": dict(self.stats.by_chain),
            "by_category": dict(self.stats.by_category),
        }


_store: LabelStore | None = None


def get_label_store() -> LabelStore:
    global _store
    if _store is None:
        _store = LabelStore().load()
    return _store
